version: "3"
services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
